### ISSUE TITLE
Library functions as internals

### ISSUE THREAD

**Issue by slothbag** [o0ragman0o/LibCLLi#1]
Hi, I was just reading through your library, I have manually created a Linked List for my contract but would be nice to replace it with a standard library like this.

Are you sure you need to create the library functions as internals?  I have created many libraries that accept custom storage structs (by ref) without using internal?

It seems like it should be possible to deploy this library independently?

**Comment by o0ragman0o** [comment]
I probably wouldn't use that particular library now...  I've simplified it
quite a bit but am yet to push.

I'd be interested in how you're passing by reference without using
internal.  It would be much preferable.

**Comment by o0ragman0o** [comment]
I probably wouldn't use that particular library now...  I've simplified it quite a bit but am yet to push.

I'd be interested in how you're passing by reference without using internal.  It would be much preferable.

**Comment by slothbag** [comment]
I keep my state structs in a separate library and import it into both the calling contract and the library, so both contracts refer to the same data structs.

```
library libState {
   struct myStruct {
   }
}
```

Then the library looks like this

```
import 'libState';
library myLib {
   function doSomething(libState.myStruct storage tmpStruct) {
   }
}
```

In fact you probably just need the state struct only to exist in the library.. should work just the same.

Oh, and probably a modern solc, 0.3.6+

**Comment by o0ragman0o** [comment]
Have just pushed my latest.  Drops the dataIndex and various other existential state variable from the struct and reduced the whole thing back to `mapping (uint => mapping (bool => uint))`.

**Comment by o0ragman0o** [comment]
I'm leaving these functions `internal` as it results in significantly smaller bytecode in the contract.

**Comment by slothbag** [comment]
No worries :)

As far as I understand it, having them as internal means the byte code gets imported into the calling contract.  Where as a non internal would include the byte code in the library contract itself and the calling contract only gets the signatures.

Anyway, thanks for this library.

**Comment by o0ragman0o** [comment]
Yes that's correct, however in the  case of these relatively simple functions, the in-lined byte code of the functions is smaller than the external library linkage/call bytecode. It also means that complex types can be passed as parameters without any fuss.
