### ISSUE TITLE
Unused variable in LibCLLi

### ISSUE THREAD

**Issue by terraflops1048576** [o0ragman0o/LibCLLi#4]
It appears that on Line 132 of LibCLL.sol, there is a function:
`function exists(CLL storage self, int n)`

However, the body of the function checks only whether the list exists, not whether the node exists (it ignores n). It's interesting to note that this is different than the signature and specification of the function of the same name in LibCLLu; I believe that it should be:
`return self.cll[n][PREV] != HEAD || self.cll[n][NEXT] != HEAD;`

I would make a pull request, but I'm rather new to Solidity and am not so confident of my observation.

**Comment by o0ragman0o** [comment]
Thanks.
I use to have a node existential function but such tests were trivial to do in the application rather than the library and so was no longer needed.
This function testing list existence should have been the int equivalent of the uint exists() function.
